### ISSUE TITLE
col-push and col-pull are missing

### ISSUE THREAD

**Issue by erunyon** [twbs/bootstrap-rubygem#102]
After installing beta 1 I noticed that col-push and col-pull are missing. They were removed in [this commit](https://github.com/twbs/bootstrap-rubygem/commit/b156edfee2b9629ad4751ee2a118a04f824ef9eb#diff-7846bbcd5737052787acc2c5f86717cf). Was this intentional?

**Comment by glebm** [comment]
Yes. See https://github.com/twbs/bootstrap.
