### ISSUE TITLE
Why is there no 4.0.0 beta version yet but the npm/bower versions do

### ISSUE THREAD

**Issue by robvdl** [twbs/bootstrap-rubygem#107]
rubygem version only seems to go upto 4.0.0.alpha6

**Comment by robvdl** [comment]
I notice there are some commits labelled 4.0.0-beta but there is no tag yet

**Comment by glebm** [comment]
Strange that a tag didn't get pushed, but the rubygem is there:
https://rubygems.org/gems/bootstrap/versions/4.0.0.beta

**Comment by robvdl** [comment]
also the docs page shows this:

npm install bootstrap@4.0.0-beta
gem install bootstrap -v 4.0.0.alpha6
bower install bootstrap#v4.0.0-beta

note the alpha6, that is what I found odd

**Comment by glebm** [comment]
This has been fixed in https://github.com/twbs/bootstrap/pull/23289 but a new version of the docs hasn't been pushed yet
