### ISSUE TITLE
Relax Popper.js dependency

### ISSUE THREAD

**Issue by tagliala** [twbs/bootstrap-rubygem#109]
Hi,

Popper.js dependency is specified as `^1.12.3` in Bootstrap's [package.json](https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L74)

as far as I can tell, `^1.12.3` is the equivalent of `'~> 1.12', '>= 1.12.3'` in rubygems. At the moment, ['~> 1.11.1'](https://github.com/twbs/bootstrap-rubygem/blob/master/bootstrap.gemspec#L14) does not allow to update to 1.12.3:

```
Bundler could not find compatible versions for gem "popper_js":
  In Gemfile:
    popper_js (~> 1.12.3)

    bootstrap (~> 4.0.0.beta) was resolved to 4.0.0.beta, which depends on
      popper_js (~> 1.11.1)
```

**Comment by glebm** [comment]
Hi, popper.js is specified as `^1.11.0` in the last released version: https://github.com/twbs/bootstrap/blob/v4.0.0-beta/package.json#L71

I'll relax the dependency on the next update.

**Comment by tagliala** [comment]
Thanks!

As far as I understand, `^1.11.0` should allow all Popper.js version from `'>= 1.11.0'` to `'< 2.0'`, so the equivalent in rubygems should be `~> 1.11`.

**Comment by glebm** [comment]
Oh, you're right, will fix.
