### ISSUE TITLE
How to enable Flexbox after using this gem ?

### ISSUE THREAD

**Issue by tusharkhatiwada** [twbs/bootstrap-rubygem#11]
Hello,

I have installed this gem on one of my local project and have imported bootstrap using:
```
@import "bootstrap"
```
I guess it doesn't use the new **Flexbox** only with this simple configuration.
Please guide me on **how to enable Flexbox Mode** with this gem.

Thanks

**Comment by clemensg** [comment]
https://github.com/twbs/bootstrap-rubygem/blob/master/assets/stylesheets/_bootstrap-flex.scss
