### ISSUE TITLE
Issue when using theme

### ISSUE THREAD

**Issue by Immortalin** [twbs/bootstrap-rubygem#110]
When using this [theme](https://bootswatch.com/darkly/), I am getting the following error:
```Sass
\a Sass::SyntaxError: (x: 0, y: 0) isn't a valid CSS value.
```

This is my configuration:
```sass
@import "darkly/variables";
//Custom bootstrap variables must be set or imported *before* bootstrap.
@import "bootstrap";
@import "darkly/bootswatch";
```
The theme folder is placed in the same folder as `application.scss`

**Comment by glebm** [comment]
That's a Bootstrap 3 theme, this is Bootstrap 4.

**Comment by Immortalin** [comment]
@glebm I used the bootstrap 4 branch.

**Comment by glebm** [comment]
Please report the issue with the theme and not with Bootstrap
