### ISSUE TITLE
Update gem to account for relaxation of the popper js version numbers

### ISSUE THREAD

**Issue by jeffreyguenther** [twbs/bootstrap-rubygem#114]
Will a new gem of the beta be released to allow users to use the relaxed popper versions? 

We need this so that we can access the positioning fixes that are coming of out popper. With the old gemspec we're locked to the 1.11.x stream.

**Comment by glebm** [comment]
We're not planning on releasing a new version until the next beta, but you can lock the gem at this commit instead if you need a newer version of Popover:

```ruby
gem 'bootstrap', git: 'https://github.com/twbs/bootstrap-rubygem',
     # v4.0.0.beta with the Popover version fix:
     ref: 'b4048df3d26d7ae6520703ba38782f4a7b6d5a3c'
```
