### ISSUE TITLE
columns don't stack on iPhone

### ISSUE THREAD

**Issue by dedekm** [twbs/bootstrap-rubygem#115]
I'm using
`gem 'bootstrap', '~> 4.0.0.alpha6'`
after deploying my app, I encountered weird bug on my iPhone
columns don't stack

even simple stuff like:
```
<body>
  <div class="container-fluid">
    <div class="row main">
      <div class="col-xs-12 col-sm">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
      <div class="col-xs-12 col-sm">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </div>
  </div>
</body>
```
I have set `meta name="viewport"`, and other responsive stuff works (.hidden-sm-up etc...)

weird is that when I link css file from Bootstrap CDN, it works fine

probably it's problem of compiler or something, i'm new to this, so not sure where to exactly to post this 
anybody had same problem?

**Comment by glebm** [comment]
Check which version you've linked from the CDN and compare to the one you have installed.

**Comment by dedekm** [comment]
I linked 4.0.0.alpha6
I even copied linked version to my app, and I still didn't work

beta has removed .hidden-* classes, which I use, so I can't easily upgrade

**Comment by glebm** [comment]
Then something is wrong with you variable overrides.

**Comment by dedekm** [comment]
I don't override any variables, it doesn't work even with no custom scss at all
