### ISSUE TITLE
Reordering columns doesn`t work anymore!

### ISSUE THREAD

**Issue by twetzel** [twbs/bootstrap-rubygem#116]
after updating from `alpha6` to `beta` all my col reordering is broken.
I`m using it as described [here](https://v4-alpha.getbootstrap.com/layout/grid/#reordering)

I had `col-md-6 push-md-6` and `col-md-6 pull-md-6` which was working like a charm till the update! .. Also tried `flex-first' and 'flex-last' = no effekt!

**Comment by twetzel** [comment]
**Update:** when I go back to `4.0.0.alpha6` reordering works again, so its clearly a bug in `beta` release or missing documentation of new usage / removed functionality

**Comment by glebm** [comment]
https://github.com/twbs/bootstrap/releases/tag/v4.0.0-beta

> Updated the grid to drop push, pull, and offset in favor of new `.order-` modifiers and margin utilities.
