### ISSUE TITLE
No support for hidden-xs-up?

### ISSUE THREAD

**Issue by boxOfAces** [twbs/bootstrap-rubygem#117]
I have the following code in a view:

```
<button type="button" tabindex="500" title="Abort ongoing upload" class="btn btn-secondary hidden-xs-up">
    <i class="fa fa-ban"></i>  
    <span class="hidden-xs-up">Cancel</span>
</button>
```
The Bootstrap v4 documentation mentions that 'hidden-xs-up' (which has replaced the erstwhile 'hidden-xs') will hide the particular element from devices which are 'xs' & upwards. Sadly, this doesn't seem to happen in my case and the button appears. Infact, there are some other elements too with the class, but they appear too.

In the Chrome debugger window, there are no styles associated with the class. Is there no support for this in the gem?

**Comment by glebm** [comment]
You're reading the alpha docs while using the beta.
See the beta docs instead: https://getbootstrap.com/docs/4.0/migration/#responsive-utilities

**Comment by boxOfAces** [comment]
Oh! my bad...Thanks a lot
