### ISSUE TITLE
Loading //= require bootstrap in application.js still using v4-Alpha-6

### ISSUE THREAD

**Issue by RigoTheCEO** [twbs/bootstrap-rubygem#120]
Loading `//= require bootstrap` in my application.js file still uses v4-alpha scripts even though I installed the gem as beta 1. So this causes things like dropdowns not to work, although a very easy workaround is simply using `//= require bootstrap-sprockets`, which uses the correct script versions.

**Comment by omouse** [comment]
Thanks for this, I also bumped into this issue with respect to navigation menus not working correctly.
