### ISSUE TITLE
README does not specify full application.js ordering

### ISSUE THREAD

**Issue by dcecile** [twbs/bootstrap-rubygem#127]
Right now the README says to add 3 entries to `application.js` but does not say where to add them.

I tried adding `jquery3`, `popper`, and `bootstrap` like this, which seemed to work fine...

```
//= require rails-ujs
//= require turbolinks
//= require jquery3
//= require popper
//= require bootstrap
//= require_tree .
```

...until I tried using [data-confirm-modal](https://github.com/ifad/data-confirm-modal), and I found that `$.rails` wasn't getting set, which caused `data-confirm-modal` to assume a non-Rails environment (effectively disabling its initialization).

Moving `//= require jquery3` before `//= require rails-ujs` resolved the issue for me, but to help others avoid similar problems, maybe it the README could be more explicit about the `application.js` changes?

**Comment by glebm** [comment]
The data-confirm-modal shouldn't use `$.rails` as `rails-ujs` does not use jQuery. Better report it there. This has nothing to do with this gem.

**Comment by dcecile** [comment]
@glebm Sorry for the confusion; I'll convert this to an issue on the `data-confirm-modal` side.

I'm not quite sure if `rails-ujs` really doesn't indirectly use jQuery, and I'm not sure if the use of `$.rails` can be removed, but let's see how it goes :wink:
