### ISSUE TITLE
Missing Popper.js in Sinatra app

### ISSUE THREAD

**Issue by unijewski** [twbs/bootstrap-rubygem#129]
Hi guys, I'm currently working on my Sinatra application and I'm getting an issue with Popper.js. I did everything as it's written in README (sprockets + bootstrap rubygem), I put
```ruby
//= require popper
//= require bootstrap-sprockets
```
into `application.js` and dropdowns in my view don't work. I visited the source code, clicked `app.js` and I'm getting:
```
throw Error("Sprockets::FileNotFound: couldn't find file 'popper' with type 'application/javascript'\nChecked in these paths: \n  /Users/me/.rvm/gems/ruby-2.4.1/gems/bootstrap-4.0.0.beta2.1/assets/stylesheets\n  /Users/me/.rvm/gems/ruby-2.4.1/gems/bootstrap-4.0.0.beta2.1/assets/javascripts\n  /Users/me/Code/my-app/app/assets/stylesheets\n  /Users/me/Code/my-app/app/assets/javascripts\n  (in /Users/me/Code/my-app/app/assets/javascripts/app.js:1)")
```
I know that `popper_js` is required in the gem so what am I doing wrong?

**Comment by glebm** [comment]
The popper_js gem doesn't currently register itself with Sprockets outside Rails.
For now, you'll need to manually call `Sprockets.append_path`

**Comment by unijewski** [comment]
Well, I did it as you mentioned but there's still something wrong. According to [Sinatra recipes](http://recipes.sinatrarb.com/p/asset_management/sprockets) I set up everything in `app.rb` so it looks like:
```ruby
set :environment, Sprockets::Environment.new

environment.append_path "assets/stylesheets"
environment.append_path "assets/javascripts"

environment.js_compressor  = Uglifier.new(harmony: true) # because it was complaining about ES6 after adding popper
environment.css_compressor = :scss

get "/assets/*" do
  env["PATH_INFO"].sub!("/assets", "")
  settings.environment.call(env)
end
```
and my `app.js` looks like:
```
//= require jquery3
//= require popper
//= require bootstrap-sprockets
```
so within `assets/javascripts` except `app.js` I added two files: `jquery.js` because `jquery-rails` is not supported with Sinatra and `popper.js`. Currently I'm not getting any errors while visiting the source file, however dropdowns aren't still working.

**Comment by glebm** [comment]
You've copied some `popper.js` file to your javascripts directory, but what you want is the file in the `popper_js` gem.  Remove `popper.js` from your javascripts folder, then add:

```ruby
environment.append_path File.join(
    Gem::Specification.find_by_name('popper_js').gem_dir, 'assets', 'javascripts')
```

**Comment by unijewski** [comment]
Awesome, now it works. 👍  Thanks!

**Comment by glebm** [comment]
Since `popper_js` v1.12.9, the gem registers itself with Sprockets even without Rails, so the above is no longer necessary.
