### ISSUE TITLE
Is there a difference between this gem and the one generated by Rails Assets?

### ISSUE THREAD

**Issue by jrguenther** [twbs/bootstrap-rubygem#13]
Is there a difference between this gem and the gem generated by rails-assets? We're starting a new project using the 4.0 and wonder which is the better option.

**Comment by glebm** [comment]
This gem structures assets in a more Railsy way, adds a dependency on autoprefixer-rails, and provides an optional Sprockets manifest for JS dependencies. It is best to use this gem and not the rails-assets version.
