### ISSUE TITLE
Bootstrap 4 styles for scaffolding

### ISSUE THREAD

**Issue by ryanoff** [twbs/bootstrap-rubygem#134]
Is it possible to add Bootstrap styles to scaffolding. For [Bootstrap 3 gem](https://github.com/seyhunak/twitter-bootstrap-rails), you could use the following code:
```
rails g scaffold Post title:string description:text
rake db:migrate
rails g bootstrap:themed Posts
```

**Comment by glebm** [comment]
The gem you've linked is not the official bootstrap 3 gem. Rails scaffolding is out of scope for this gem.
