### ISSUE TITLE
"@extend %grid-column" on line 22

### ISSUE THREAD

**Issue by sposinff** [twbs/bootstrap-rubygem#138]
v4.0.0
I am getting the following error

`
You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend %grid-column" on line 22 of /.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootstrap-4.0.0/assets/stylesheets/bootstrap/mixins/_grid-framework.scss.
`

This is with sass-rails 5.0.7.

**Comment by glebm** [comment]
Try updating to the latest version of Sass

**Comment by sposinff** [comment]
Another gem is blocking me from doing that. I will work on that and report back. Thank you.

**Comment by sposinff** [comment]
Sorry, I was on the wrong branch. We do have sass 3.5.5.
`
bundle list | grep sas
  * font-awesome-sass (4.7.0)
  * sass (3.5.5)
  * sass-listen (4.0.0)
  * sass-rails (5.0.7)`

**Comment by sposinff** [comment]
Line 27 of this same file too.

And then
```From "@extend .form-control-sm" on line 132 of /.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootstrap-4.0.0/assets/stylesheets/bootstrap/_input-group.scss```

I am going to be patient now.

**Comment by glebm** [comment]
I suggest you look for an error in your setup or code. Did you upgrade from a previous version of Bootstrap? Are you using Bootstrap mixins heavily?

Looking at the full Sass backtrace may help you find the issue.

**Comment by sposinff** [comment]
Yes, we were previously on bootstrap-sass (3.3.5). I removed other bootstrap related gems, includes, etc. and still have this error. Any other ideas?

**Comment by glebm** [comment]
The migration from v3 to v4 is not trivial. There are *a lot* of changes: https://getbootstrap.com/docs/4.0/migration/.

The backtrace may be visible in the web browser if you hover over the error message.

**Comment by sposinff** [comment]
I am going to have to give up for now. Thank you for your suggestions.
