### ISSUE TITLE
Bootstrap mixin doesn't work

### ISSUE THREAD

**Issue by tastemeru** [twbs/bootstrap-rubygem#14]
When I'm trying to deploy with capistrano or run `rake assets:precompile` I get the error
```
Sass::SyntaxError: Undefined mixin 'make-container'.
  (in /Users/Andrew/Sites/designvideo/app/assets/stylesheets/base/global.scss:36)
```
Here is the global.scss line 36
```
	.container-fluid {
	  max-width: 95em;
	  @include make-container();
	    padding-left: 8%;
	    padding-right: 8%;
	}
```
and `application.scss`
```
@import "base/variables";

@import "bootstrap";

@import "base/widgets.scss";
@import "base/global.scss";

@import "font-awesome-sprockets";
@import "font-awesome";
@import "select2";
@import "select2-bootstrap";
@import "styles/authors.scss";
@import "styles/conferences.scss";
...
```

Actually in development environment everything looks great. Error gets just when I'm deploying. 
What could be wrong with mixins there?

**Comment by tastemeru** [comment]
I've found the answer. In my assets.rb was the line `Rails.application.config.assets.precompile += [/.*\.js/,/.*\.css/]` and it was compiling all scss files twice I guess. I commented this line and now everything works

**Comment by glebm** [comment]
By [default](http://guides.rubyonrails.org/asset_pipeline.html#precompiling-assets), Rails 4 precompiles application.css, application.js, and all non-js/css css files under app/assets: application.scss first compiles to application.css, which Rails then precompiles. You shouldn't need to modify the precompile array at all for this use case.

**Comment by cvrebert** [comment]
@glebm So, should this be closed?
