### ISSUE TITLE
RubyRacer Segfault with this gem

### ISSUE THREAD

**Issue by wiredin** [twbs/bootstrap-rubygem#140]
/home/mweiss/.rvm/gems/ruby-2.4.3/gems/therubyracer-0.12.3/lib/v8/function.rb:13: [BUG] Segmentation fault at 0x0022be34
ruby 2.4.3p205 (2017-12-14 revision 61247) [armv7l-linux-eabihf]

Anyone have any ideas? Only occurs after adding bootstrap gem to my Gemfile.

**Comment by glebm** [comment]
Try switching to mini_racer

**Comment by wiredin** [comment]
Thanks, that helped me down the right path! Ended up needing newest version of libv8 for arm. Installed the binary from https://rubygems.org/gems/libv8/versions/6.3.292.48.1-arm-linux Still using The Ruby Racer.
