### ISSUE TITLE
File to import not found or unreadable: bootstrap/utilities-background.

### ISSUE THREAD

**Issue by MarkMurphy** [twbs/bootstrap-rubygem#15]
[bootstrap/utilities-background](https://github.com/twbs/bootstrap-rubygem/blob/master/assets/stylesheets/bootstrap/_utilities-background.scss) is not present in [4.0.0.alpha1](https://github.com/twbs/bootstrap-rubygem/tree/v4.0.0.alpha1/assets/stylesheets/bootstrap)

**Comment by glebm** [comment]
It is not, alpha1 is older than this file. You can use the master version directly instead.
