### ISSUE TITLE
"Autoprefixer doesn’t support Node v4.2.6" error on brand new rails app

### ISSUE THREAD

**Issue by installero** [twbs/bootstrap-rubygem#162]
That's a pity the bootstrap gem doesn't work with a plain rails installation:

https://asciinema.org/a/ZLxYks3GZqnJpUm3YNAPGUiEW

```
Autoprefixer doesn’t support Node v4.2.6. Update it.
```

``` sh
$ node -v
v11.1.0

$ nvm use system
$ node -v
v7.10.0

```

**Comment by glebm** [comment]
> That's a pity the bootstrap gem doesn't work with a plain rails installation:

Your Rails installation has absolutely nothing to do with your NodeJS version.

In fact, a "plain Rails" installation comes with rails/webpacker which [requires Node v6+](https://github.com/rails/webpacker/blob/88a253ed42966eb2d5c997435e9396881513bce1/package.json#L11).

**Comment by installero** [comment]
Both my system and default versions of NodeJS are higher than 6.

**Comment by installero** [comment]
```
$ nvm use system
Now using system version of node: v7.10.0 (npm v3.5.2)
install@btron:qkspace$ which nodejs
/usr/bin/nodejs
install@btron:qkspace$ /usr/bin/nodejs -v
v4.2.6
install@btron:qkspace$ node -v
v7.10.0
```

> Check that you don't accidentally have a nodejs executable left-over from some manual installation or something.

Thank's you're right!
