### ISSUE TITLE
README says "Ensure that sprockets-rails is at least v2.3.2" but latest version is 2.3.1

### ISSUE THREAD

**Issue by pekalicious** [twbs/bootstrap-rubygem#168]
As the title suggests, the README file says to ensure that sprockets-rails is at least 2.3.2 but doing so results in a bundle error "Could not find gem 'sprockets-rails (~> 3.2.2) x64-mingw32' in any of the gem". A quick look at the RubyGems.org site shows that the [latest version](https://rubygems.org/gems/sprockets-rails/versions) is 2.3.1

**Comment by jblac** [comment]
A little late but, look at your version `3.2.2` should be `2.3.2`
