### ISSUE TITLE
No release notes for 4.2.1

### ISSUE THREAD

**Issue by mattbrictson** [twbs/bootstrap-rubygem#169]
The latest version of the bootstrap gem published to rubygems is 4.2.1, but I don't see any mention of it in the [CHANGELOG](https://github.com/twbs/bootstrap-rubygem/blob/master/CHANGELOG.md) or in the [GitHub Releases](https://github.com/twbs/bootstrap-rubygem/releases).

Digging through the [commits](https://github.com/twbs/bootstrap-rubygem/compare/v4.1.3...v4.2.1), it seems that 4.2.1 included a switch from `sass` to `sassc`, which seems like a big deal. Are there any upgrade concerns or is this 4.2.1 a drop-in replacement for 4.1.x?

**Comment by glebm** [comment]
Ruby Sass is deprecated. This should be a drop-in replacement.
