### ISSUE TITLE
Cannot use Toasts or Popovers

### ISSUE THREAD

**Issue by CharlieIGG** [twbs/bootstrap-rubygem#172]
Hello, I'm using Rails 5.2, with sprockets-rails 3.2.1.

For some reason, everything else seems to work, but both `popover` and `toast` won't work for me:
`$(...).toast is not a function`. 

Everything else seems fine (i.e. Carousel, Tooltips, etc). 

Any clues?

**Comment by rosshettel** [comment]
I'm having the same issue

**Comment by CharlieIGG** [comment]
I'm going to close this. 

@rosshettel for me the issue was caused by the fact that I had two conflicting versions of jQuery in the project without realizing it. This was caused because of requiring jQuery in my assets pipeline manually, but I was using the Dashkit template, which was also loading a different version of jQuery separatedly. You might want to look into that.
