### ISSUE TITLE
Update Bootstrap v4.4.1

### ISSUE THREAD

**Issue by GuillaumeWrobel** [twbs/bootstrap-rubygem#181]
By running `rake update[v4.4.0]`

see [release 4.4.0](https://github.com/twbs/bootstrap/releases/tag/v4.4.0)

:+1:

**Comment by glebm** [comment]
Might want to wait for 4.4.1 https://github.com/twbs/bootstrap/issues/29743

**Comment by GuillaumeWrobel** [comment]
[4.4.1 released](https://github.com/twbs/bootstrap/releases/tag/v4.4.1)
