### ISSUE TITLE
Does this works with RoR 6.x?

### ISSUE THREAD

**Issue by ejuniorls** [twbs/bootstrap-rubygem#187]

**Comment by tejasbubane** [comment]
I have used it with a basic Rails `6.0.2` project and it works without any issues.

**Comment by Souravgoswami** [comment]
Hi, just getting started with rails. Whenever I `require('bootstrap-sprockets')`, I get error `Error: Cannot find module 'bootstrap-sprockets'`. Also, I can't have navbar toggle features with this gem even though JQuery's `$()` syntax is working fine from browser's console.

**Comment by tejasbubane** [comment]
As mentioned in the README, you have to rename `application.css` to `application.scss` and use `@import "bootstrap";` after removing all requires.

**Comment by Souravgoswami** [comment]
My application.scss looks like this:
```
@import "bootstrap" ;

body {
	margin: 0 ;
}
```
I have also asked help about this issue here:
https://stackoverflow.com/questions/61662956/error-cannot-find-module-bootstrap-sprockets

**Comment by glebm** [comment]
This gem is for use with sprockets, not webpacker. For webpacker, use the npm package instead.

**Comment by ejuniorls** [comment]
thks guys. it worked!

**Comment by robertsimoes** [comment]
@glebm Thoughts on updating the `README` to include instructions w.r.t the new webpack changes in Rails 6? I can make a PR if needed

**Comment by StevenXL** [comment]
> @glebm Thoughts on updating the `README` to include instructions w.r.t the new webpack changes in Rails 6? I can make a PR if needed

Knowing that this gem is for used with sprockets and not webpack would be a great addition to the documentation.

**Comment by robertsimoes** [comment]
PR if interested. @StevenXL @glebm https://github.com/twbs/bootstrap-rubygem/pull/195
