### ISSUE TITLE
ExecJS::RuntimeUnavailable error after installing gem

### ISSUE THREAD

**Issue by iamnader** [twbs/bootstrap-rubygem#193]
Hi, I've installed this gem and am using it fine locally.

On my CI environment (CircleCI) which is using a linux node docker image, I'm getting this error when running a `bundle exec rake db:migrate` to setup the environment: `ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime.`

I've isolated the changes to adding this gem version 4.5 to my gemfile.

Rails 6.0.2.2
Ruby 2.6.5

Thoughts?

**Comment by glebm** [comment]
Install NodeJS or another JavaScript runtime.

**Comment by lukewduncan** [comment]
lol i know this is 3 years old. but you should be able to specify a ruby image defined with node now in circleCI. E.g.

```
docker:
      - image: cimg/ruby:3.2.1-node
```
