### ISSUE TITLE
5.0.0-alpha1 not available

### ISSUE THREAD

**Issue by arndeash** [twbs/bootstrap-rubygem#194]
According to the Bootstrap v5 documentation, there should be a Bootstrap 5 alpha-version of the gem:
https://v5.getbootstrap.com/docs/5.0/getting-started/download/

However it doesn't seem to be the case:
https://rubygems.org/gems/bootstrap

**Comment by jramiresbrito** [comment]
Same problem here:

```Fetching gem metadata from https://rubygems.org/.
Could not find gem 'bootstrap (~> 5.0.0.pre.alpha1)' in any of the gem
sources listed in your Gemfile.
```

```
ERROR:  Could not find a valid gem 'bootstrap' (= 5.0.0.pre.alpha1) in any repository
```

**Comment by glebm** [comment]
5.0.0.alpha1 released
