### ISSUE TITLE
Changelog for latest releases

### ISSUE THREAD

**Issue by ShockwaveNN** [twbs/bootstrap-rubygem#197]
Hi, seems several latest releases do not have a changelog (not in changelog file nor in GitHub releases page)
Could this be fixed? I've using dependabot to update my requirements and empty changelog is not very good on upgrade process

**Comment by glebm** [comment]
There were no changes to the gem-specific code since the last entry.
The changelog for Bootstrap itself is available here https://github.com/twbs/bootstrap/releases and won't be duplicated in this repo.

**Comment by ShockwaveNN** [comment]
Maybe it's a good idea to add changelog entries like these?

```
## 4.5.2
No changes to gem-specific code.
Bootstrap changes are [here](https://github.com/twbs/bootstrap/releases/tag/v4.5.2)
```
