### ISSUE TITLE
Incompatible units: 'px' and 'em' - Error after upgrading gem

### ISSUE THREAD

**Issue by toadle** [twbs/bootstrap-rubygem#20]
Hey guys, 

I just changed our `Gemfile` to reflect the latest changes.

from 

```
gem 'bootstrap', git: 'https://github.com/twbs/bootstrap-rubygem'
```
which got locked to rev `5ef4dee608c93e6b3d7538500bbac4d05c79b94b` in our `Gemfile.lock`

to 

```
gem 'bootstrap', '~> 4.0.0.alpha3'
```

After running to usual `bundle install` my rails-app wouldn't load anymore. 

I get this error:

```
ActionView::Template::Error (Incompatible units: 'px' and 'em'.):
```

This seems to have to do with the order of our included `sass`-files. We have a `variables.scss` that changes the Bootstrap-Variables to reflect our custom theme. 

We have it BEFORE `bootstrap` in our `application.css.scss` in order to have the variables set correctly.

```
@import 'variables';
@import 'bootstrap';
```

This causes the error. 

When doing 

```
@import 'bootstrap';
@import 'variables';
```

It does indeed work but then some colors are off in our custom-theme. 

Any hints?

**Comment by thomas-mcdonald** [comment]
If you import variables after bootstrap you won't be overriding any of the Bootstrap variables. Off the top of my head it's likely one of the variables in that file changed from em -> px and you are still overriding it as em?

**Comment by cvrebert** [comment]
Closing due to lack of response from OP.
