### ISSUE TITLE
Bootstrap 5 depends on popper > 2.x

### ISSUE THREAD

**Issue by blacklist-arcc** [twbs/bootstrap-rubygem#206]
I got some errors in my rails project after updating the gem to bootstrap 5 beta. The official docs page shows that popper.js is included using version 2.x

**Comment by glebm** [comment]
I've pushed a 2.6.0 release of popper https://rubygems.org/gems/popper_js/versions/2.6.0

**Comment by blacklist-arcc** [comment]
Sure but the dependency of the bootstrap gem targets popper v1
https://github.com/twbs/bootstrap-rubygem/blob/cd3fbc224696165e8512fff126cc514307a3cdb5/bootstrap.gemspec#L17

**Comment by blacklist-arcc** [comment]
@glebm you may can review the dependency of the ruby gem here =) thanks for your fast response!

**Comment by glebm** [comment]
Thanks for pointing this out, I've bumped it on master https://github.com/twbs/bootstrap-rubygem/commit/615e415ec4c4de8852bbc826f78d881a845e8da0

**Comment by glebm** [comment]
v5.0.0.beta2 has been released
