### ISSUE TITLE
Modal stopped working from 5.0.0 beta3 -> 5.0.0 stable

### ISSUE THREAD

**Issue by luccasmaso** [twbs/bootstrap-rubygem#217]
Apparently the modal component "api" has not changed. I know that internally the lib has been refactored to work with backdrop.js. 

Error
<img width="747" alt="Screenshot 2021-05-13 at 10 42 01" src="https://user-images.githubusercontent.com/1427231/118134033-dc485300-b3d7-11eb-8a8f-d3fa8f5f6b25.png">
<img width="1039" alt="Screenshot 2021-05-13 at 10 43 32" src="https://user-images.githubusercontent.com/1427231/118134283-216c8500-b3d8-11eb-9897-1471f8b7256c.png">

I was wondering if it is something related with sprockets order imports (last commit diff below), [as similar reports](https://stackoverflow.com/questions/67440523/bootstrap-v5-modal-show-issue) points that.
<img width="1244" alt="Screenshot 2021-05-13 at 10 40 26" src="https://user-images.githubusercontent.com/1427231/118133810-a30fe300-b3d7-11eb-9688-8965b04c7dfa.png">

**Comment by luccasmaso** [comment]
I think it was solved by version 5.0.1 PR

https://github.com/twbs/bootstrap/pull/33853

**Comment by glebm** [comment]
Released 5.0.1
