### ISSUE TITLE
Bootstrap 5.1.0

### ISSUE THREAD

**Issue by defsdoor** [twbs/bootstrap-rubygem#224]
The bootstrap 5.1.0 pages reference installing 5.1.0 version of this gem, but there isn't a 5.1.0 branch/tag.

Is there a chance of a 5.1.0 branch ?

**Comment by glebm** [comment]
Released v5.1.0

**Comment by defsdoor** [comment]
Awesome - thanks.  

I had a go at doing this myself and made a similar change to update/js.rb   I only noticed you had done so (so quickly) when I logged back in to github to do a fork so I could raise a pull request :D
