### ISSUE TITLE
Works with Rails 7?

### ISSUE THREAD

**Issue by marcuxyz** [twbs/bootstrap-rubygem#228]
Hello guys,

This `gem `works with `Rails 7`?

**Comment by collimarco** [comment]
I'm also on Rails 7 and I can't find a way to add the required Javascript using this gem...

Please update to Rails 7 (at least the docs)

**Comment by collimarco** [comment]
As a workaround I have used:

```
$ ./bin/importmap pin bootstrap
```

Then in `app/javascript/application.js`:

```
import * as bootstrap from "bootstrap"
```

However this is a workaround and this gem needs to be updated (at least the docs).

**Comment by coorasse** [comment]
It's working great with Rails 7. I wrote how here: https://dev.to/coorasse/rails-7-bootstrap-5-and-importmaps-without-nodejs-4g8, but I think my blog post should actually be integrated in this gem documentation. Also, I'd change the [engine](https://github.com/twbs/bootstrap-rubygem/blob/master/lib/bootstrap/engine.rb) to behave like the [turbo-rails one](https://github.com/hotwired/turbo-rails/blob/main/lib/turbo/engine.rb#L29-L35) and precompile popper and bootstrap by default

**Comment by crazy-creator-traveler** [comment]
Hello, Bootstrap community!

It would be great to update the documentation to work with Rails 7+ using import map > https://github.com/rails/importmap-rails .
The above solution of the @coorasse  solves the problem.

Thanks for your contribution and time!

**Comment by arenzel** [comment]
The solution proposed by @coorasse in his post is the way to go: works on a Rails 7.0.2 app was not generated with the `--css=bootstrap` command. 👌

**Comment by equivalent** [comment]
to keep it simple use : 

-  use Ralis 7 importmaps for Bootstrap JS. (the ` ./bin/importmap pin bootstrap` command
- use this gem (twbs/bootstrap-rubygem) for sprockets CSS 


no need to use the --css=bootstrap (as that needs npm)
