### ISSUE TITLE
Update github repository description

### ISSUE THREAD

**Issue by coorasse** [twbs/bootstrap-rubygem#229]
It states "Bootstrap 4 rubygem for Rails...." while is already at 5.
<img width="1314" alt="CleanShot 2022-01-12 at 11 41 56@2x" src="https://user-images.githubusercontent.com/1319150/149125364-cc3cfb8e-e7cb-4d69-beb6-15a572f0dfd3.png">

This is therefore reflected in the Google results:
<img width="623" alt="CleanShot 2022-01-12 at 11 42 58@2x" src="https://user-images.githubusercontent.com/1319150/149125506-8a2e5172-8610-4435-bdb3-23b1360477ba.png">

I'd propose to remove any version number from here and just leave "Bootstrap rubygem for Rails..."

**Comment by glebm** [comment]
Thanks, updated
