### ISSUE TITLE
Does the gem load all appropriate file to my app?

### ISSUE THREAD

**Issue by tgermer** [twbs/bootstrap-rubygem#230]
Hi everyone,

I would love to use this gem, but I don't understand how it working.
I am not new to Jekyll and gems.

Should it load all appropriate files to my app or should I need to download files from getbootsprap.com?

I think that I did everything mentioned in the readme.

<img width="218" alt="image" src="https://user-images.githubusercontent.com/21098461/150021612-cabe6cc4-472d-4e4c-bf28-0b6a19c401e6.png">

Thank you very much for your help.
Tristan

**Comment by db0sch** [comment]
If you added the bootstrap gem to your Gemfile, and then added `@import "bootstrap"` to your `application.scss`, then you should be good to go.
