### ISSUE TITLE
Release 4.6.2 to rubygems?

### ISSUE THREAD

**Issue by jrochkind** [twbs/bootstrap-rubygem#238]
bootstrap 4.6.2 does not seem to have been released to rubygems, although it has a tag in the repo and has been released to npm.

https://rubygems.org/gems/bootstrap/versions

https://github.com/twbs/bootstrap/tree/v4.6.2
https://www.npmjs.com/package/bootstrap/v/4.6.2

As other bootstrap versions are all released to rubygems... is it possible to get 4.6.2 released to rubygems? 

I am interested in it for the replacement of the deprecated `color-adjust` with `print-color-adjust`, for Autoprefixer. As the bootstrap rubygem has a gem dependency on `autoprefixer-rails `, it's a relevant fix.

**Comment by timwis** [comment]
I came here looking for this fix as well

**Comment by aseroff** [comment]
+1

**Comment by glebm** [comment]
Released
