### ISSUE TITLE
cannot load such file -- sassc

### ISSUE THREAD

**Issue by mursalinir** [twbs/bootstrap-rubygem#240]
I am new in ruby on rails, currently I am a learner. I tried to add bootstrap in my apps. 

I am facing an error when I am trying to renaming app/assets/stylesheets/application.css => app/assets/stylesheets/application.scss. It's shows **cannot load such file -- sassc** in my test server (puma).

![2022-10-02 23_23_26-Action Controller_ Exception caught — Mozilla Firefox](https://user-images.githubusercontent.com/7901643/193467462-df526d95-de0b-42bb-88e8-da1eed2d9fac.jpg)

Details about my application:

- Ruby version: 3.1.2
- Rails version: 7.0.4
- OS: Windows 11

I don't know what's the problem and what is solution.

**Comment by Faq** [comment]
If your project is public, You could share it, so it would be as example for others to check.

**Comment by shivam091** [comment]
@mursalinir Hello.

Are you having `gem "sprockets-rails"` in your Gemfile and following config in your configuration `Rails.application.config.assets.css_compressor = :sass`? If not, can you please add it and check if this error still persist.

Your application stylesheet file is ending with extension `.scss` hence it required preprocessor to work in Rails app.

Thank you.

**Comment by zachGl** [comment]
@mursalinir Can you try to restart your rails server?
This should fix the issue.

**Comment by mursalinir** [comment]
Thank you so much guys. The issue have been solved.
