### ISSUE TITLE
Rails Assets is going away.

### ISSUE THREAD

**Issue by radicaled** [twbs/bootstrap-rubygem#27]
See https://github.com/rails-assets/rails-assets/issues/291

The README recommends using it to install Tether as a dependency. Should probably be changed to using `wget` to pull the correct Tether version into `vendor/assets/javascripts`

**Comment by arbourd** [comment]
It is currently down, as well.

**Comment by synth** [comment]
I have no idea why rails-assets-tether wasn't put on rubygems. I personally need it on rubygems because I'm working on a gem for my organization(a major university) that is a sort of "meta"-gem, a gem that pulls together a number of gems and preset configurations for apps produced by the university. Therefore, I need the dependency put into the gemspec, not the Gemfile, and thus needs to be on rubygems. 

That said, I cloned the repo, built the gem, and put it on rubygems: https://rubygems.org/gems/rails-assets-tether

Happy to see, in two days snce publishing, google has indexed it already: http://lmgtfy.com/?q=rails-assets-tether :)

**Comment by mateuszdw** [comment]
Thanks for that @synth. So instead documented
```
source 'https://rails-assets.org' do
   gem 'rails-assets-tether' , '>= 1.1.0'
end
```
just use
`gem 'rails-assets-tether'`

**Comment by glebm** [comment]
Rails Assets is not going away: https://github.com/rails-assets/rails-assets/issues/312

**Comment by twe4ked** [comment]
Using rails-assets can slow down `bundle install` quite dramatically. Could we have a gem for tether under the twbs org? /cc @glebm

**Comment by jakegavin** [comment]
I ran into that as well so I wrapped [Tether](https://github.com/HubSpot/tether) in a ruby gem.
https://github.com/jakegavin/tether-rails/
https://rubygems.org/gems/tether-rails
I haven't worked with bootstrap and tether extensively but so far that is working for me. I've been planning on looking into a way of optionally including it in `twbs/bootstrap-ruby` but haven't gotten around to it yet.

If twbs org ownership is important, I could to transfer the `tether-rails` rubygem name and/or that repo over to twbs.

**Comment by synth** [comment]
@jakegavin how is your gem different than rails-assets-tether gem I moved to rubygems, if at all?

**Comment by jakegavin** [comment]
@synth  ¯\_(ツ)_/¯ It's probably not any different. Sorry. I'm just not super familiar with how rails assets works. Looks your gem was automatically created. So is there no github repo? Where/how do I create a PR updating it to 1.2.0?

I don't really care what the path forward is but I would support a transition off of Rails assets if thats what the maintainers are interested in. @twe4ked brought up the idea of adding a tether gem under the twbs org so I just wanted to mention that I'm have the `tether-rails` name on ruby gems and would gladly transfer it to them if thats what they want to do.

**Comment by synth** [comment]
rails-assets-tether on rubygems is just a repackaged version of whats on rails assets. There is no github repo for it. I would recommend creating one, or perhaps, using the repo you created "tether-rails". My only concern was to not have two gems doing the same thing(causing confusion) and opt to use the official codebase(rails-assets-tether) as a starting point for forks. I also support having the codebase owned by twbs github org. The only thing that should not be done, imho, is hosting gems on rails-assets as its not possible for those gems to be listed as dependencies by other gems.

**Comment by twe4ked** [comment]
@jakegavin's gem looks a bit more complete than the rails-assets generated one. I'm going to be using that one personally. If it ends up being the one that Bootstrap recommends it might make sense to have it controlled by the Bootstrap team but I don't mind personally.

@synth If you would prefer people using yours it would probably need to be on GitHub (or similar) with a README etc.

My main point is not having to rely on rails-assets which is quite slow (maybe it's an Australian internet thing).

**Comment by synth** [comment]
It doesn't matter to me, and its certainly not "mine". I merely moved the version from rails-assets to rubygems so I too could have access. I have no attachment to any solution other than moving off rails assets too :)

**Comment by glebm** [comment]
Has anyone spoken to @HubSpot or @zackbloom about them providing an official rubygem?

**Comment by zackbloom** [comment]
We are happy to help, do you need us to merge something into the main project, or is it just about ownership of the Gem?

**Comment by twe4ked** [comment]
@glebm Sounds like they're happy to help. What would be the best solution in your eyes?

**Comment by glebm** [comment]
It would be best to have a script that packages Tether into a RubyGem and publishes it, and have it run as part of the release procedure of Tether. This way the gem will always be up to date and published by the same team that maintains Tether, with little effort on their part. Perhaps someone can provide such as a script in a PR to Tether?
