### ISSUE TITLE
Main branch is ahead of rubygem’s gem, dartsass-rails is not included

### ISSUE THREAD

**Issue by thooams** [twbs/bootstrap-rubygem#275]
## Rubygem code
![Capture d’écran 2024-01-15 à 16 19 45](https://github.com/twbs/bootstrap-rubygem/assets/1183066/6ee095f6-b2e7-4811-af2e-7f65267c5410)

## Github main branch code
![Capture d’écran 2024-01-15 à 16 24 56](https://github.com/twbs/bootstrap-rubygem/assets/1183066/442ea87a-7a25-4b0e-a3d2-8950f990c213)

**Comment by glebm** [comment]
The main branch is ahead of the release version, yes, that is the case with most GitHub repos.
What are you trying to say?

**Comment by thooams** [comment]
Ok, so the documentation is wrong in the README,  because it says for gem version "5.3.2" that dartsass-rails is supported.
![Capture d’écran 2024-01-17 à 11 08 01](https://github.com/twbs/bootstrap-rubygem/assets/1183066/df021988-1274-482b-b20a-48b994f2fde6)

**Comment by glebm** [comment]
Yeah, the `main` branch is always work-in-progress. We bump the version in the readme when we release the new version.

The readme for 5.3.2 is at https://github.com/twbs/bootstrap-rubygem/tree/v5.3.2
