### ISSUE TITLE
autoprefixer

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap-rubygem#29]
I found that the autoprefixer only runs if i add `gem "autoprefixer-rails"` to my Gemfile too?

**Comment by glebm** [comment]
Well, autoprefixer-rails is specified as a runtime dependency so it shouldn't be necessary to add it manually?

**Comment by bassjobsen** [comment]
i found i does only install but does not run without adding it to the app Gemfile. Maybe i did something wrong?

**Comment by glebm** [comment]
Perhaps I'm confused about how transitive dependencies work.

If you remove autoprefixer-rails from Gemfile and then run:

```ruby
require 'autoprefixer-rails'
```

in the console, does this return `true`?

**Comment by adelivuk** [comment]
I can confirm @bassjobsen issue, without specifying the gem in the `Gemfile`, it doesn't work.

In my **application.scss**:

```
@import "bootstrap";

li{
  background: linear-gradient(to top, black, white);
  display: flex
}
```

With `gem 'autoprefixer-rails'` included in the `Gemfile`:

![screen shot 2016-03-02 at 11 46 27](https://cloud.githubusercontent.com/assets/6178877/13458296/be278f92-e06c-11e5-8192-aedbda4d1356.png)

And without:

![screen shot 2016-03-02 at 11 46 54](https://cloud.githubusercontent.com/assets/6178877/13458297/be29a78c-e06c-11e5-9173-bc8c1371a352.png)

Also, [here's the same question on SO](http://stackoverflow.com/a/32284059/1763929).

**Comment by lotap** [comment]
I can also confirm this behavior.
Mac OSX 10.11.3 - El Capitan
FireFox 44
Rails 4.2.5

**Comment by glebm** [comment]
Should be fixed on master
