### ISSUE TITLE
Flexbox

### ISSUE THREAD

**Issue by maithreya** [twbs/bootstrap-rubygem#31]
How do i change the display to flex from table if i install this gem? As bootstrap 4 supports flex grid

**Comment by woto** [comment]
include instead of bootstrap

```
@import "bootstrap-flex";
```

it's not more than https://github.com/twbs/bootstrap-rubygem/blob/master/assets/stylesheets/_bootstrap-flex.scss

**Comment by Startouf** [comment]
The [flexbox Bootstrap page ](http://v4-alpha.getbootstrap.com/getting-started/flexbox/) mentions recompiling in order to use the flexbox mode. I would suggest adding a line to the readme to explain that you have the choice between the float/flexbox

**Comment by etcook** [comment]
@glebm Would you be willing to accept a PR on README to cover flexbox? I had to search for it in the issues myself.

**Comment by glebm** [comment]
@etcook Sure
