### ISSUE TITLE
File to import not found or unreadable: bootstrap/custom.

### ISSUE THREAD

**Issue by cristianrosu** [twbs/bootstrap-rubygem#35]
While trying to custom load separate files from bootstrap, "bootstrap/custom" gives this error: File to import not found or unreadable: bootstrap/custom. 

Same for bootstrap/tags. All other work fine.

**Comment by amnwebmaster** [comment]
Also experienced the same probably on the same two files:
bootstrap/custom
bootstrap/tags

**Comment by schovi** [comment]
Same here, but after some digging I found, that master is different than `4.0.0.alpha3` tag.
You have to open code with that tag and use custom bootstrap from there https://github.com/twbs/bootstrap-rubygem/blob/v4.0.0.alpha3/assets/stylesheets/_bootstrap.scss
