### ISSUE TITLE
rename @import reference

### ISSUE THREAD

**Issue by joryhatton** [twbs/bootstrap-rubygem#39]
i'm attempting to override a default import of `bootstrap` via bootstrap-sass that's being pulled from another gem.  i should be able to use this in a fork if i simply rename the `@import` reference and corresponding files (i was trying `@import "bootstrap_4"`.  i can't seem to get it working though.  any suggestions?

**Comment by joryhatton** [comment]
Is there a quick solution for this?  I can't get this working because it directly conflicts with the [spree frontend](https://github.com/spree/spree/tree/master/frontend) gem which uses `bootstrap-sass`.  Is there a way to rename the `@import` reference here to something like `bootstrap_4`?

**Comment by cvrebert** [comment]
For personal support questions or how-to questions, please use one of the community forums (https://github.com/twbs/bootstrap/blob/master/README.md#community) instead of the bug tracker.
Thanks!
