### ISSUE TITLE
Popover: center position

### ISSUE THREAD

**Issue by cheneveld** [twbs/bootstrap-rubygem#40]
I would like to use a popover but pass 'center middle' as the attachment value to Tether.  

The tooltip AttachmentMap only allows 4 values.  Would it be possible to pass the input value through if it is not found in the AttachmentMap?  Or maybe add a center value?

I would be happy to make this change and submit a pull request, but I am unsure of contribution protocol for this project.

**Comment by glebm** [comment]
Please submit issues upstream to https://github.com/twbs/bootstrap
