### ISSUE TITLE
.col-xs-12 now required on every responsive col?

### ISSUE THREAD

**Issue by sbleon** [twbs/bootstrap-rubygem#48]
Thanks for all of your work on v4! I'm enjoying working with it thus far! 😄 

Sometime since the release of Alpha 3, the grid appears to have changed and now every responsive col seems to need to have `.col-xs-12` in order to size correctly in XS viewports.

Correct width without col-xs-12 in alpha3:
```
<div class="row" style="background-color: yellow">
  <div class="col-md-6 offset-md-3" style="background-color: blue">
    <div class="card">
      <div class="card-block">
        Correct width without col-xs-12
        <br>
        dc6648900ffe8609188a7bf904bd765a492471b9
        <br>
        4.0.0.alpha3
      </div>
    </div>
  </div>
</div>
```
![screen shot 2016-07-28 at 1 39 45 pm](https://cloud.githubusercontent.com/assets/198711/17223055/e924e138-54c8-11e6-957e-243e5d8d7d22.png)

Incorrect width without col-xs-12 in f6a7b7bf41ea628b61693597be299c4257f93079:
```
<div class="row" style="background-color: yellow">
  <div class="col-md-6 offset-md-3" style="background-color: blue">
    <div class="card">
      <div class="card-block">
        Incorrect width without col-xs-12
        <br>
        f6a7b7bf41ea628b61693597be299c4257f93079
      </div>
    </div>
  </div>
</div>
```
![screen shot 2016-07-28 at 1 38 17 pm](https://cloud.githubusercontent.com/assets/198711/17223086/1be211fe-54c9-11e6-98d3-53508c9e74ad.png)

To correct width in f6a7b7bf41ea628b61693597be299c4257f93079, we must add `.col-xs-12` to every responsive col in our application:
```
<div class="row" style="background-color: yellow">
  <div class="col-xs-12 col-md-6 offset-md-3" style="background-color: blue">
    <div class="card">
      <div class="card-block">
        Correct width with col-xs-12
        <br>
        f6a7b7bf41ea628b61693597be299c4257f93079
      </div>
    </div>
  </div>
</div>
```
![screen shot 2016-07-28 at 1 37 55 pm](https://cloud.githubusercontent.com/assets/198711/17223107/2f460e1c-54c9-11e6-9550-f4cfef0bbdc1.png)

I wanted to make sure that this change was intentional and see if anyone can explain the reasoning behind it. I think it makes for a poorer developer experience, both because of the extra typing and because of the change in behavior from what we're used to in v3. It also seems to be at odds with a mobile-first philosophy, where you don't have to do anything for XS because it is assumed to be the default.

**Comment by glebm** [comment]
The alpha3 release of this gem is actually much older than the upstream release. There is now a new version out that corresponds to the upstream Alpha 3: https://rubygems.org/gems/bootstrap/versions/4.0.0.alpha3.1.

I don't know if this behaviour is different in the new version, but if it isn't then this issue should be raised in the [upstream tracker](https://github.com/twbs/bootstrap) as this repository just handles the rubygem-specific code.

**Comment by sbleon** [comment]
Thanks, Gleb, for pointing out the upstream project, and for clarifying the odd release date incongruence between the two. I was pretty confused by that last week!

For the record, the behavior I described was a bug :-) , but had [already been fixed upstream](https://github.com/twbs/bootstrap/pull/20349) when I reported it here. Doh!
