### ISSUE TITLE
glyphicons not working

### ISSUE THREAD

**Issue by dfl** [twbs/bootstrap-rubygem#50]
I'm not seeing glyphicons in my app.
e.g.       `<span class="glyphicon glyphicon-phone" aria-hidden="true"></span>`

some other bootstrap gems say I need to  `@import "bootstrap-sprockets"` but seems that file doesn't exist?

**Comment by cvrebert** [comment]
That's to be expected. `bootstrap-rubygem` is for Bootstrap v4, and Glyphicons were removed in Bootstrap v4. See http://v4-alpha.getbootstrap.com/migration/#components 

For the Bootstrap v3 RubyGem, see https://github.com/twbs/bootstrap-sass instead.
