### ISSUE TITLE
Update gem to alpha 4

### ISSUE THREAD

**Issue by tordans** [twbs/bootstrap-rubygem#53]
There is an alpha 4 now http://blog.getbootstrap.com/2016/09/05/bootstrap-4-alpha-4/.
Is there a timeline to update the gem, yet?

Thanks, Tobias

**Comment by evaneykelen** [comment]
I just submitted a PR: https://github.com/twbs/bootstrap-rubygem/pulls

**Comment by glebm** [comment]
Done
