### ISSUE TITLE
"Using a Bootstrap Template"

### ISSUE THREAD

**Issue by prietodcarlos** [twbs/bootstrap-rubygem#58]
Hi all! Thank you for this opportunity on this awesome class!

I've finally caught up in the class but i ran into an issue on "Using a Bootstrap Template".
Localhost3000 doesn't load the new template. It only shows the site of the old class. 
I verified the instructions several time and tried several things but still the new template doesn't come up. 

I committed the code to github with a message explaining my problem. Is it possible anybody can help me out?

**Comment by prietodcarlos** [comment]
Got it working! it was a problem in the routing. 
However, the only thing i'm missing is adding the image.

**Comment by thomas-mcdonald** [comment]
I'm not sure what class you're taking, but this is not the place you should be looking for support.
