### ISSUE TITLE
No utility classes available

### ISSUE THREAD

**Issue by aesnyder** [twbs/bootstrap-rubygem#59]
None of the utility classes from the documentation are available when using this gem.

I have tried specifically `@import "bootstrap/utilities";`

No dice. Any ideas?

**Comment by donv** [comment]
What utility classes are you missing?

**Comment by renatopanda** [comment]
@donv "text-right" for instance. Am i missing something?

**Comment by erunyon** [comment]
@aesnyder (four months later) Did you find a solution? The class you're mentioning is in https://github.com/twbs/bootstrap-rubygem/blob/master/assets/stylesheets/bootstrap/utilities/_text.scss. So you should have them as long as you're including `@import "bootstrap/utilities";`
