### ISSUE TITLE
Rails generator

### ISSUE THREAD

**Issue by glebm** [twbs/bootstrap-rubygem#6]
Would be cool to have a generator for Rails that performs all the setup steps. /cc @thomas-mcdonald

**Comment by thomas-mcdonald** [comment]
50/50 on this, we previously punted all Rails stuff to other gems, and it increases the chance that we end up needing to release outside of Bootstrap 4.y.z due to Rails issues.

Would be nice to bring it in and provide a more complete solution though...

**Comment by glebm** [comment]
Good point, closing.
