### ISSUE TITLE
Cannot load bootstrap-sprockets.js within RefineryCMS

### ISSUE THREAD

**Issue by javinto** [twbs/bootstrap-rubygem#61]
I have a RefineryCMS 3.x application where I want to start using Bootstrap 4 alpha 5.

The Bootstrap CSS works fine but the application cannot load the bootstrap-sprockets.js or bootstrap.js file:

couldn't find file 'bootstrap-sprockets' with type 'application/javascript'
Checked in these paths: 
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/speakingurl-rails-8.0.2/lib
  /Users/javinto/Workspace/myproject.com/app/assets/images
  /Users/javinto/Workspace/myproject.com/app/assets/javascripts
  /Users/javinto/Workspace/myproject.com/app/assets/stylesheets
  /Users/javinto/Workspace/myproject.com/vendor/assets/javascripts
  /Users/javinto/Workspace/myproject.com/vendor/assets/stylesheets
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/underscore-rails-1.8.3/vendor/assets/javascripts
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/gmaps4rails-2.1.2/vendor/assets/javascripts
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/rails-assets-tether-1.3.7/app/assets/javascripts
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/rails-assets-tether-1.3.7/app/assets/stylesheets
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/refinerycms-wymeditor-1.1.0/app/assets/images
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/refinerycms-wymeditor-1.1.0/app/assets/javascripts
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/refinerycms-wymeditor-1.1.0/app/assets/stylesheets
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/jquery-ui-rails-5.0.5/app/assets/images
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/jquery-ui-rails-5.0.5/app/assets/javascripts
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/jquery-ui-rails-5.0.5/app/assets/stylesheets
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/refinerycms-core-3.0.4/app/assets/images
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/refinerycms-core-3.0.4/app/assets/javascripts
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/refinerycms-core-3.0.4/app/assets/stylesheets
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/refinerycms-core-3.0.4/vendor/assets/javascripts
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/refinerycms-i18n-3.0.1/app/assets/images
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/jquery-rails-4.2.1/vendor/assets/javascripts
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/coffee-rails-4.1.1/lib/assets/javascripts
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/turbolinks-source-5.0.0/lib/assets/javascripts
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/font-awesome-sass-4.7.0/assets/stylesheets
  /Users/javinto/.rvm/gems/ruby-2.2.2@refinery3/gems/font-awesome-sass-4.7.0/assets/fonts

Copying in the bootstrap files and folder does work, but is not the preferred situation off course. 

My application.js:
//= require jquery2
//= require jquery_ujs
//= require tether
//= require bootstrap-sprockets
//= require turbolinks
//= require underscore
//= require gmaps/google
//= require_tree .

I tried using Bootstrap 4 alpha 5 within another Rails 4 project and that works. 

Could it have something to do with engines clashing? Overriding paths? Is this a RefineryCMS issue?

**Comment by jcoyne** [comment]
@javinto it seems odd that bootstrap isn't one of the paths that it looked for. What does your Gemfile look like?  Does it have `gem 'bootstrap'` in it?

**Comment by javinto** [comment]
Thank you for your message. I had Bootstrap loaded within my gemfile but after loading RefineryCMS. 

After moving Bootstrap ahead of RefineryCMS within my gemfile everything now seems to work. Don't know why I did not try that before ....

The issue can be closed.

**Comment by javinto** [comment]
Solution is to load Bootstrap before RefineryCMS in your gemfile.
