### ISSUE TITLE
Ruby on Rails setup instructions don't work for RoR 5.0.0.1 / Ruby 2.3.0

### ISSUE THREAD

**Issue by csjohn** [twbs/bootstrap-rubygem#62]
I created a fresh Rails 5 app (`rails 5.0.0.1`) and ran through readme instructions for rails (part a). My ruby version is `2.3.0` and I'm running off on OSX 10.12.1.

My `Gemfile` includes:
```
gem 'bootstrap', '~> 4.0.0.alpha5'

source 'https://rails-assets.org' do
    gem 'rails-assets-tether', '>= 1.1.0'
end
```
and despite following the steps quite carefully, I'm unable to get bootstrap styles to work. I ran through the steps twice (starting with `rails new app`) each time.

I see no console errors in browser, and it seems like the assets are loading. Screenshot of chrome's `sources` tab:
![screen shot 2016-12-02 at 4 41 00 pm](https://cloud.githubusercontent.com/assets/979350/20851415/4f52911e-b8ae-11e6-95b3-eb7ddab93963.png)

I don't see any errors in the server console either. Pages that I try to throw some bootstrap stylin' onto just look broken. Below is an example of some simple markup with the expected rendered page (taken from https://getbootstrap.com/components/#navbar-text) and the actual rendered page from my machine.

**Markup:**
```
<ul class="nav nav-pills">
  <li role="presentation" class="active"><a href="#">Home</a></li>
  <li role="presentation"><a href="#">Profile</a></li>
  <li role="presentation"><a href="#">Messages</a></li>
</ul>
```

**Expected:**
![screen shot 2016-12-02 at 4 46 19 pm](https://cloud.githubusercontent.com/assets/979350/20851525/0d4296ec-b8af-11e6-9b92-60b42e28bdbc.png)

**Actual:**
![screen shot 2016-12-02 at 4 46 28 pm](https://cloud.githubusercontent.com/assets/979350/20851526/12ac456a-b8af-11e6-9300-016bf3e6e525.png)

**Comment by glebm** [comment]
This is bootstrap 4 alpha, but you're using bootstrap 3 classes and documentation

**Comment by csjohn** [comment]
Oh jeeze. Doing too many things at once and didn't notice😩  thanks!
