### ISSUE TITLE
Code not up to date

### ISSUE THREAD

**Issue by casey-stinnett** [twbs/bootstrap-rubygem#63]
@I may be mistaken, but it seems that the styling included is not up to date. I just downloaded the latest styling from getbootstrap.com and it includes some navbar styling that is not included in the navbar styling in here. In here, I cannot find `.navbar-default` like exists in the Bootstrap code. Is this intentional or am I missing something completely? @glebm

**Comment by jcoyne** [comment]
This gem is for Bootstrap 4. Are you looking for Bootstrap 3? Try here: https://github.com/twbs/bootstrap-sass/

**Comment by casey-stinnett** [comment]
Of course. That was a silly mistake. Woops!
