### ISSUE TITLE
Dropdown stopped work with 

### ISSUE THREAD

**Issue by nascimento** [twbs/bootstrap-rubygem#68]
After update from 4.0.0.alpha5 to 4.0.0.alpha6 dropdown-menu toggle stopped work.

**Comment by glebm** [comment]
See this [release notes](https://github.com/twbs/bootstrap/releases/tag/v4.0.0-alpha.6) entry:

> - Renamed some `.active`,  all `.in`, and all `.open` classes for our JavaScript powered components for more consistent naming. For example, instead it's now `.collapse.show` instead of  `.collapse.in` and `.show > .dropdown-menu` instead of `.open > .dropdown-menu` to better communicate the visibility of elements.
