### ISSUE TITLE
bootstrap-sprockets import order in application.js wrong in Rails 5 apps?

### ISSUE THREAD

**Issue by Mikeysax** [twbs/bootstrap-rubygem#69]
I've noticed in Rails 5 applications that the correct import order in application.js should be:
```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap-sprockets
//= require_tree .
```
Otherwise it messes with other destroy actions within Rails 5 applications. It might have to do with turbolinks.

**Comment by kftwotwo** [comment]
what about the tether?
