### ISSUE TITLE
Troubles using custom SASS variables

### ISSUE THREAD

**Issue by krsyoung** [twbs/bootstrap-rubygem#71]
I'm currently trying to customize the colour scheme of bootstrap using the SASS variables:

```sass
// application.scss
@import 'bootstrap/variables';    // from the gem, needed for variable declarations
@import "_boostrap-variables";    // my customizations

// Custom bootstrap variables must be set or imported *before* bootstrap.
@import "bootstrap";
```

My custom variables are in `_boostrap-variables.scss` which looks something like this:
```sass
// _boostrap-variables.scss
// already defined $new- variables here ...

$brand-primary:             $new-blue;
$brand-success:             $new-green;
$brand-info:                $new-teal;
$brand-warning:             $new-orange;
$brand-danger:              $new-red;
$brand-inverse:             $new-gray-dark;
```

However, none of these variables take effect.  For example the `$new-blue` does not show for my `btn-primary`.   One thing I did notice, if I uncomment `$btn-primary-bg` definition in my `_boostrap-variables.scss` then it does take effect:

```sass
// all good
$btn-primary-bg:                 $brand-primary;
```

Although this works it seems like it isn't right to have to uncomment all of the variables.

Any chance something in the gem is overriding things?  Or more likely I have an ordering problem with how I'm making use of the custom variables?

**Comment by krsyoung** [comment]
Ok, well maybe typing everything thing out helped.  I've found the following seems to work:

```sass
// application.scss
@import "colours";    // my custom colours
@import 'bootstrap/variables';    // from the gem, needed for variable declarations
@import "_boostrap-variables";    // other customizations, i.e. $border-radius

// Custom bootstrap variables must be set or imported *before* bootstrap.
@import "bootstrap";
```

Where `colours.scss` looks like:

```sass
// colours.scss
$yes-malachite: #20BF55;
$yes-dark-imperial-blue: #0B4F6C;
$yes-cyan: #01BAEF;
$yes-ghost-white: #FBFBFF;
$yes-sonic-silver: #757575;

$brand-primary:             $yes-dark-imperial-blue;
$brand-success:             $yes-malachite;
```

With this layout the `$brand-primary` takes effect.  Does this make sense or am I getting lucky?

**Comment by tagliala** [comment]
> Does this make sense or am I getting lucky?

Yes, it makes sense to me.

In Sass, you are supposed to define your custom variables before the default one.

Ref: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_
