### ISSUE TITLE
JQuery missing on Rails 5.1

### ISSUE THREAD

**Issue by PAMulligan** [twbs/bootstrap-rubygem#76]
I created a new Rails app using 5.1. I also installed this gem as per the instructions in the readme. When I load my index page, it looks fine, but I noticed in dev tools that there is an uncaught error: "Bootstrap's Javascript requires JQuery" I can fix this by manually installing the jquery-rails gem, and including the line "//= require jquery" before the rails-ujs include in my application.js, but is this the correct way to handle this?

**Comment by glebm** [comment]
Yes, this is the correct way to handle this. We should document it before Rails 5.1 release

**Comment by adrianvalenz** [comment]
Not documented yet, or is it? I didn't see it while reading the instructions in the README

**Comment by glebm** [comment]
Closed by #83
