### ISSUE TITLE
font-family not inherited from body by input, button, select, textarea

### ISSUE THREAD

**Issue by jasonkarns** [twbs/bootstrap-rubygem#77]
reboot.css declares that `input`, `button`, `select` and `textarea` should inherit their `font` from `body` (as defined in normalize.css). https://github.com/twbs/bootstrap-rubygem/blob/26a742889f415d1f6b7205929ba10543fae639a9/assets/stylesheets/bootstrap/_reboot.scss#L314-L315

However, this comment is a lie. normalize.css does not declare any of these elements to inherit their font. https://github.com/twbs/bootstrap-rubygem/blob/26a742889f415d1f6b7205929ba10543fae639a9/assets/stylesheets/bootstrap/_normalize.scss#L257-L260

**Comment by glebm** [comment]
This issue is only for the rubygem-specific issues. Please report all framework issues to https://github.com/twbs/bootstrap.

**Comment by jasonkarns** [comment]
opened as https://github.com/twbs/bootstrap/issues/21588
