### ISSUE TITLE
Focus styles not shared with hovered buttons

### ISSUE THREAD

**Issue by jasonkarns** [twbs/bootstrap-rubygem#78]
Button variants in the hover and focus states are intended to share some properties, as indicated in code comment: https://github.com/twbs/bootstrap-rubygem/blob/79c3fc026cbc1428e783135ec4ecfb7d71889497/assets/stylesheets/bootstrap/mixins/_buttons.scss#L15

This is consistent with Bootstrap 3 behavior, where the color and background color for a button variant are shared between hover and focus states: https://github.com/twbs/bootstrap/blob/9b7d1406b922300c5d01e99026e4fffc67445185/less/mixins/buttons.less#L11-L21 (well, border-color is only 12% darker for hover, whereas 25% darker for focus; but background-color and color are both identical between the two states.)

However, in bootstrap 4, the button-variant mixin only mixes in the `:hover` state, not the `:focus` state. (see: https://github.com/twbs/bootstrap-rubygem/blob/79c3fc026cbc1428e783135ec4ecfb7d71889497/assets/stylesheets/bootstrap/mixins/_buttons.scss#L16 and https://github.com/twbs/bootstrap-rubygem/blob/79c3fc026cbc1428e783135ec4ecfb7d71889497/assets/stylesheets/bootstrap/mixins/_hover.scss#L1-L13

The end result is that buttons in Bootstrap 4 do not get the same color styling when focused as they do when hovered. (Indeed, anchor elements with .btn classes still end up with the `a:focus` colors.)

**Comment by glebm** [comment]
This issue is only for the rubygem-specific issue. Please report all framework issues to https://github.com/twbs/bootstrap.

**Comment by jasonkarns** [comment]
Possibly related to https://github.com/twbs/bootstrap/pull/21539

**Comment by jasonkarns** [comment]
Fixed by https://github.com/twbs/bootstrap/pull/21539 but no idea when that will end up in a released gem.

**Comment by glebm** [comment]
The gem is updated along with the upstream releases. You can fork and update yourself by running `rake update` from the fork.

**Comment by jasonkarns** [comment]
But the source sass seems to be copied/pasted into this repo? This setup makes it quite frustrating attempting to track down behavior when the v4-dev branch source (from "main" repo) is different from the master source in this gem repo.

**Comment by glebm** [comment]
The framework code is copied and adapted for Rails from the upstream repo by the `rake update` command. The commit hash of the upstream repo at which it was synced is available at https://github.com/twbs/bootstrap-rubygem/blob/master/lib/bootstrap/version.rb.

**Comment by jasonkarns** [comment]
Cool. I'd recommend having this noted in Readme or Contributing.

But better yet, eliminate the source from this repo entirely. If the sass source in this repo is a build artifact (which it apparently is, since it is simply copied down from the other repo and not actively maintained in this repo), then it shouldn't be committed to the repo; for the same reason the compiled CSS shouldn't be committed to this repo. For what purpose does the sass even exist in this repo? Best as I can tell, there is no reason for it to even be versioned. The update rake command would pull as it does now, tests can be run, and the gem can be built all using the same steps as it does currently; all without having the sass copied into this repo, which just leads to confusion and misdirection.

**Comment by jasonkarns** [comment]
All of this is IMO, of course. This thread is sufficiently off the original ticket. And closed (appropriately). I'm just sharing my piece. take as you will :)

**Comment by glebm** [comment]
Ruby gems cannot directly depend on non-gems via a native mechanism.

While build steps *can* be performed during install, these steps should not depend on network access as that is not compatible with certain types of secure installs.

So I don't think it's possible to provide a Bootstrap rubygem without bundling the Bootstrap source with it.

The Readme should of course contain the information about `BOOTSTRAP_SHA`.

**Comment by jasonkarns** [comment]
I'm not saying the gem would pull the source down at install time. I'm talking about build time. A gem is just a zip file. If the files are on the local machine at the time the gem is built/packaged, and they are specified in the gemspec `files` property, then they'll be included in the gem archive. There's no requirement that they _also_ be in the git repo.

This is how all kinds of build artifacts are built (compiled, generated, whatever) and included in a gem without being committed to the repo.

**Comment by jasonkarns** [comment]
I can open a separate issue thread (or maybe even a PR) to flesh out this conversation a bit more if it's warranted. If there are any action items that come from this, it's probably a bit weird to have them on this ticket.

**Comment by glebm** [comment]
>  If the files are on the local machine at the time the gem is built/packaged, and they are specified in the gemspec files property, then they'll be included in the gem archive

That would make no different to the users though.
The only difference is that the git repo would be slimmer, but it's not a problem currently.
It would also make it impossible to see the changes between releases directly on GitHub (since updating is not just copy-paste, e.g. it generates the sprockets javascripts file).

What would the motivation be for this change?

>  it's probably a bit weird to have them on this ticket.

Sure
