### ISSUE TITLE
Navbar dropdown in not working in production

### ISSUE THREAD

**Issue by fjahr** [twbs/bootstrap-rubygem#80]
The configuration of ```application.js``` suggested in the readme does not work for me in production. The navbar dropdown, implemented exactly as in the documentation, fails to open. It only works there if I require both ```bootstrap``` and ```bootstrap-sprockets``` there. But if I do that it does not work in development mode.

Works only in production:
```
//= require jquery
//= require tether
//= require bootstrap
//= require bootstrap-sprockets
//= require jquery_ujs
//= require turbolinks
//= require_tree .
```

Works only in development:
```
//= require jquery
//= require tether
//= require bootstrap-sprockets
//= require jquery_ujs
//= require turbolinks
//= require_tree .
```

I have read a lot about similar issues in prior versions and I have tried a lot of require sequences but none of them have been working in both requirements for me. I have followed all the other configuration steps in the readme.

**Comment by fjahr** [comment]
Maybe also notable: just using ```bootstrap``` instead of ```bootstrap-sprockets``` does not work at all in development.

**Comment by fjahr** [comment]
I have it currently working by explicitly calling the dropdown function every time turbolinks reloads the page.

    //= require jquery
    //= require jquery_ujs
    //= require tether
    //= require bootstrap
    //= require turbolinks
    //= require_tree .
    
    $( document ).on('turbolinks:load', function() {
      $('.dropdown-toggle').dropdown();
    })

But I should not have to do this so I would really like to have a real answer to the problem.

**Comment by glebm** [comment]
Turbolinks compatibility is not provided by Bootstrap.
