### ISSUE TITLE
No route matches [GET] "/assets/bootstrap/dropdown.js.map"

### ISSUE THREAD

**Issue by SampsonCrowley** [twbs/bootstrap-rubygem#87]
the current engine doesn't include all necessary files correctly:

application.js:
```js
//= require jquery
//= require jquery_ujs
//= require popper
//= require bootstrap-sprockets
```
application.scss:
```css
@import "bootstrap";
```
rails 5.0.1
sprockets-rails 3.2.0

error: 
```
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/alert.js.map"):
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/button.js.map"):
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/carousel.js.map"):
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/modal.js.map"):
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/dropdown.js.map"):
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/popover.js.map"):
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/scrollspy.js.map"):
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/tab.js.map"):
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/tooltip.js.map"):
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/popover.js.map"):
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/collapse.js.map"):
```
Pretty much throws an error for every single map file

**Comment by SampsonCrowley** [comment]
there were more maps that were in the error list but I was done scrolling. you get the idea

**Comment by SampsonCrowley** [comment]
why did you close this without any response

**Comment by SampsonCrowley** [comment]
the current readme instructions aren't valid.  I have to include the precompiled meta tags in my app otherwise none of this works

With just the gem's instructions:
![screenshot from 2017-04-02 13-43-57](https://cloud.githubusercontent.com/assets/22461638/26598086/533debe2-4531-11e7-8e49-11fac3f83ab8.png)

including the stylesheet from CDN:
![screenshot from 2017-05-30 12-11-26](https://cloud.githubusercontent.com/assets/22461638/26598087/534a4e00-4531-11e7-8b1c-f3a720d3b6a4.png)

**Comment by glebm** [comment]
> why did you close this without any response

It was closed in the commit linked by GitHub above. See where it says "glebm closed this in deb364c 17 hours ago", you can click on the commit hash (#deb364c) to see the details.

> I have to include the precompiled meta tags in my app otherwise none of this works

I assume you mean the responsive meta tag? This is mentioned in the documentation: https://v4-alpha.getbootstrap.com/getting-started/introduction/#important-globals

**Comment by SampsonCrowley** [comment]
no i meant precompiled.  I had to add the links to the precompiled source, instead of use the gem for anything to work.

the responsive tag did nothing to get media queries to work with the gem version

**Comment by SampsonCrowley** [comment]
notice the line: `including the stylesheet from CDN`

**Comment by glebm** [comment]
The `master` version is not on any CDN. See #88

**Comment by badbabykosh** [comment]
"you can click on the commit hash (#deb364c) to see the details." there are no details in your commit hash. And read the manual is not a proper response. Tell the end user..."oh I fixed this with this commit (hash)...you can resolve this by using version x.y.z..go ahead and give that a try and post back to verify it has resolved your problem" End user does this and post back a big Tank you and gushes at how helpful you are and how beneficial the software is. Future visitors see thread...find solution...everyone happy. You can THEN close the issue.
