### ISSUE TITLE
Bootstrap 4 Navbar always collapsed when in Rails 5.1 application

### ISSUE THREAD

**Issue by floydj** [twbs/bootstrap-rubygem#88]
The navbar appears, but is always in 'hamburger' mode, when it should be so only in smaller screen sizes. Nav html code below is copy/pasted straight from bs4 docs, but does not work out-of-box with the gem. What am I missing here?

* Rails 5.1.1
* Ruby 2.3.3
* I have run `bundle install`
* I have restarted my rails server
* Tested in Chrome and Firefox, same result

Gemfile:
```
gem 'bootstrap', git: 'https://github.com/twbs/bootstrap-rubygem'
gem 'jquery-rails'
```

app/assets/javascripts/application.js:
```
//= require jquery3
//= require popper
//= require bootstrap
//= require turbolinks
//= require_tree .
```

app/assets/stylesheets/application.scss
```
@import "bootstrap";
```

app/views/layouts/application.html.erb
```
<!DOCTYPE html>
<html>
  <head>
    <title>Navy2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Navbar</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>
```

**Comment by glebm** [comment]
You're missing the responsive meta tag.
See the documentation: https://v4-alpha.getbootstrap.com/getting-started/introduction/#important-globals

**Comment by floydj** [comment]
Adding the meta tag doesn't fix this problem. Added it in: same result.

**Comment by glebm** [comment]
Does removing `//= require turbolinks` help?

**Comment by floydj** [comment]
Changing the class from navbar-toggleable-md to navbar-expand-md fixes things, but that's against what the BS4 docs say, unless I'm missing something. Removing turbolinks makes no difference.

**Comment by glebm** [comment]
The docs on getbootstrap.com are for alpha6 (from January), whereas you're using the master version, so it could be something has changed in the meantime.

**Comment by floydj** [comment]
Using master is what the readme recommends. Should I be using something else?

**Comment by glebm** [comment]
Bootstrap 4 is still in alpha. If you want a stable release, use Bootstrap 3.

**Comment by mohitDeshpande** [comment]
@floydj I was able to fix this issue by including popper_js gem in my Gemfile.

**Comment by rmcsharry** [comment]
Bootstrap 4 beta, Rails 5.1, same issue, cannot (yet) find a solution. Popper_js gem did not fix it (1.11.1).

**Comment by rmcsharry** [comment]
Not sure why, but these examples work with this gem:
https://www.codeply.com/go/imngr08QRi

**Comment by stan74fr** [comment]
I personally forced back to Bootstrap 4 alpha6.0

gem 'bootstrap', '= 4.0.0.alpha6'

As a consequence I also removed reference to 'poppe'r and re-added back 'tether'.

**Comment by wandersonsc** [comment]
Yeah, I was having the same issue while using 'bootstrap', '~> 4.0.0.beta',  downgrading it to 4.0.0.alpha6 did the trick for me.

**Comment by Edistra** [comment]
I was having the same issue, look at how it's done here : https://v4-alpha.getbootstrap.com/examples/navbars/

You need to wrap the navbar content in a 
`<div class="container"></div>`

Complete code :
```
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">Navbar</a>
        <div class="collapse navbar-collapse" id="navbarNav">
           <a class="nav-item nav-link" href="#">Home <span class="sr-only">(current)</span></a>
           <a class="nav-item nav-link" href="#">Features</a>
        </div>
    </div>
</nav>
```

**Comment by xxEoD2242** [comment]
I just figured out how to solve the issue of non-responsiveness with the toggleable navbar class.

Essentially, with bootstrap 4.0.0.beta2, you need to follow the instructions on the bootstrap 4.0.0.beta2 gem install and insure you that you have gem 'rails-sprockets' as well as gem 'popper_js'

What was happening to mine is that bootstrap was trying to configure the navbar and couldn't because it was saying "popper was undefined" in the console. I went back and re-did the bootstrap install and it worked, finally!

**Comment by cgibsonmm** [comment]
instead of .navbar-toggleable-* you need to use .navbar-expand-* should fix all issues
