### ISSUE TITLE
Navbars not working any longer!

### ISSUE THREAD

**Issue by kinsbrunner** [twbs/bootstrap-rubygem#89]
Hi,

I am copy&pasting the snippet to add a navbar into my view and it seems not to be working any longer. Instead, I am seeing what a small grey square beside the logo space ("Logo goes here") and none of the navbar links:

![no-navbar](https://cloud.githubusercontent.com/assets/16242832/26782237/f4796248-49c8-11e7-82ff-530b4192b559.PNG)

If I check HTML, everything seems to be there: code, css and js.
On the gemfile, I have included:
```
gem 'jquery-rails'
gem 'bootstrap', git: 'https://github.com/twbs/bootstrap-rubygem'
```

On my application js:
```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require popper
//= require bootstrap-sprockets
//= require_tree .
````

I am adding bootstrap by adding the following line into application scss:
```
@import "bootstrap";
````

Am I doing something wrong? I just checked another code which was working perfectly fine and is now similar to this one.

Regards.

Alejandro.

**Comment by glebm** [comment]
See https://github.com/twbs/bootstrap-rubygem/issues/88

**Comment by kinsbrunner** [comment]
Thanks Gleb but this did not solve my issue.

I have copy&pasted the code snippet from getbootstrap.com which is the following and which give the shown results:

```
<header id="navigation" class="home-ts-menu">
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#home">LOGO GOES HERE!</a>
      </div>

      <div id="myNavbar" class="navbar-collapse collapse">
        <div class="main-menu">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a class="smooth-scroll" href="#home">Home</a></li>
            <li><a class="smooth-scroll" href="#about">Nosotros</a></li>
            <li><a class="smooth-scroll" href="#process">Metodología</a></li>
            <li><a class="smooth-scroll" href="#contact">Contacto</a></li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>
```

But, if I paste the following snippet, it works fine:
```
<header id="navigation" class="home-ts-menu">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Navbar</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</header>
```

Also, I have adjusted gemfile:
```
gem 'jquery-rails'
gem 'bootstrap', '~> 4.0.0.alpha6'
source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.3.3'
end
```

And, also adjusted application.js:
```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require tether
//= require bootstrap-sprockets
//= require_tree .
```

Any idea of why is the official code not working?

Regards.

Alejandro.

**Comment by glebm** [comment]
getbootstrap.com is for Bootstrap 3
https://v4-alpha.getbootstrap.com/ is for Bootstrap v4.0.0.alpha6

**Comment by kinsbrunner** [comment]
My baaaad! Thanks Gleb!

**Comment by kinsbrunner** [comment]
Gleb,

I am reopening this issue as, although yesterday, mistake was mine, I still believe there are some issues with navbar.

If I try introducing official example from: https://v4-alpha.getbootstrap.com/components/navbar/#responsive-behaviors

I should be getting something like:
![navbar_expected](https://user-images.githubusercontent.com/16242832/26853559-e72daede-4ae8-11e7-86b3-61b8c3f8955b.PNG)

Instead, I am always getting the navbar with the toggle button. My intention would be to see the "normal" navbar buttons and only see the toggler for small devices. (I tried adjusting classes but did not work).

Also, I tried pushing the toggler to the right by adding ".navbar-toggler-right" class as said by the doc but still shown on the left.

![navbar_real](https://user-images.githubusercontent.com/16242832/26853634-2994cfbe-4ae9-11e7-95cf-f71cddd0967d.PNG)
(Ignore the fact of the navbar-inverse and green color)

Am I doing something wrong?

Regards.

Alejandro.

**Comment by glebm** [comment]
Looks like you are using the master branch. The documentation online is for v4.0.0.alpha6.
Inspect the Bootstrap source or compile the master documentation from https://github.com/twbs/bootstrap

**Comment by ArturMinnullin** [comment]
Hey, @kinsbrunner did you solve it? I have the same issue 😔

**Comment by vpiddem** [comment]
Hi guys! Still facing this issue. Any luck?
