### ISSUE TITLE
navbar changes from single column to single row

### ISSUE THREAD

**Issue by jasnow** [twbs/bootstrap-rubygem#9]
Upgraded our local ruby users group web site, atlrug4, from bootstrap-sass (3.3.5.1) to bootstrap-rubygem.

Changed changed Gemfile file from
```
 gem "bootstrap-sass"
```
to 
```
gem 'bootstrap', git: 'https://github.com/twbs/bootstrap-rubygem' # Version 4
source 'https://rails-assets.org' do
   gem 'rails-assets-tether', '>= 1.1.0'
end
```
And added 2 lines to app/assets/javascripts/application.js file:
```
 //= require jquery
 //= require jquery_ujs

+//= require tether
+//= require bootstrap-sprockets

 //= require bootstrap
 //= require turbolinks
 //= require_tree .
```
No changed to app/assets/stylesheets/application.scss file:
```
@import "bootstrap";
@import "variables";
@import "styles";
@import "media-queries";
@import "jobs";
@import "components/footer";
@import "components/banner";
@import "components/forms";
@import "components/navigation";
```
Add the navbar layout is:
```
      %div.navbar-collapse
        %ul.nav.navbar-nav.nav-links.navbar-left
          %li
            = link_to 'Go to Meetings', meetings_path
          %li
            = link_to 'Find Presentations', videos_path
          %li
            = link_to 'Learn Ruby', '/learn'
        %ul.nav.navbar-nav.nav-links.navbar-right
          %li
            = link_to 'Find a Job', jobs_path
          %li
            = link_to 'Hire Someone', resumes_path
```
Now the navbar is a single column vs. single row for bootstrap-sass (3.3.5.1).

To see the current 3.3.5.1 version at www.atlrug.com .

Any insight why for the different behavior?

Thanks...

**Comment by glebm** [comment]
Please submit all the style related issues to https://github.com/twbs/bootstrap.

**Comment by jasnow** [comment]
sorry

**Comment by glebm** [comment]
By the way, this Ruby gem is for Bootstrap 4, which is currently in alpha and not ready for production. Bootstrap 4 is written in Sass, so there is no need for a Sass conversion such as bootstrap-sass anymore. This gem simply packages Bootstrap 4 as is.

**Comment by jasnow** [comment]
>> alpha

Yes, I have canary apps to use to try out your gem.
