### ISSUE TITLE
Navbar not shows correctly

### ISSUE THREAD

**Issue by pandalowry** [twbs/bootstrap-rubygem#92]
Hello!

I have the following situation:

Connecting the gem according to the instructions, everything goes well.

But!

Navbar button which should hide (and be displayed on md devices) behaves as if I'm on a md device.

Tried to remove @import "bootstrap";
And used versions with the same CDN version (v4.0.0-alpha.6)
The problem goes away!

Of course, I can just download the CSS with CDN or from the assets/stylesheets folder, **but with the supplied gem's Sass something is wrong, please check!**

I use Rails 5.1 of the latest version.

**Comment by pandalowry** [comment]
my navbar code:

`  <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>    `

**Comment by pandalowry** [comment]
and navbar views this:

![](https://habrastorage.org/web/e80/59a/b0f/e8059ab0f474411ca7410087b763dd68.png)

**Comment by nvma** [comment]
Yeah, same problem. It's been like this a couple of weeks I think.

**Comment by erbogart28** [comment]
Same issue here -_-

Trying to use gems for everything.. guess I'll settle with bootstrap CDNs....

**Comment by SimonPotier** [comment]
What is happening is that the responsive media queries rules aren't loaded somehow. 
The `.collapse` class should be in `display: block` and it is not the case because media queries seem not loaded.

**Comment by kjakub** [comment]
same issue and resolved with 

`gem 'bootstrap', '~> 4.0.0.alpha6'`

**Comment by nvma** [comment]
Can confirm this resolves the issue with the navbar, but I had to remove `require popper` from application.js since rails could no longer find it.

**Comment by pandalowry** [comment]
issue from @kjakub uses tether, not popper. Its previous ver alpha 6 what i thinks.

Wait contributors voice! )

**Comment by sofiazapatazavala** [comment]
.navbar-expand-* is the current way to go. The docs aren't updated (yet), but that's how it's gonna be for Beta 1. https://github.com/twbs/bootstrap/issues/21568

**Comment by harrisnguyen94** [comment]
@sofiazapatazavala This just saved me. I was confused for 15min wonder what I did wrong.
Well, I guess that is the price we must pay for living on the edge

**Comment by pandalowry** [comment]
@sofiazapatazavala thanx, this helps me. But, docs in offisite (examples) are outdate.

**Comment by glebm** [comment]
The docs on the official website are for the latest released alpha, not for the master branch.
The online docs will be updated once a new version is released.

To see the master documentation locally, see https://github.com/twbs/bootstrap#documentation.

**Comment by fabriziobertoglio1987** [comment]
I believe it is better downloading the file from https://getbootstrap.com/docs/4.0/getting-started/theming/ and configuring this with webpack
