### ISSUE TITLE
Styles not applying with Rails 5

### ISSUE THREAD

**Issue by GusAndrianos** [twbs/bootstrap-rubygem#96]
Hello.

I am just starting with Bootstrap (Back End dev here) and I am trying to add a fixed to top navbar to my app.
The only styling that's applied is, very basic link and button styling, as well as, borders of text boxes. When I copy the code for the navbar, I only get the links that I added, equally spread out but with a plain white background and nothing like the navbar shown in the Components page.

Can you help?

**Comment by mmahalwy** [comment]
Same problem here

**Comment by GusAndrianos** [comment]
Glad I'm not alone.

**Comment by TagWolf** [comment]
I believe this is related to my issue #95

**Comment by GusAndrianos** [comment]
@TagWolf So if you do that, and copy the code for a navbar, does it appear the same as the model on their site?

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by TagWolf** [comment]
All I know is that this repo's gem doesn't compile half of the CSS needed for bootstrap.
It misses tons of stylings. Offset columns don't exist for instance.

If you try using an offset column on your site is it currently working?

For example:
<div class="row">
  <div class="col-md-2 offset-md-10">
    <p>This should be on the right side of the page</p>
  </div>
</div>

**Comment by glebm** [comment]
Here is the source of your troubles. You are looking at the docs for the last released alpha. The master branch has changed quite a bit since then. The master docs are not available online, but you can compile them from source at https://github.com/twbs/bootstrap.

**Comment by bbugh** [comment]
@TagWolf I had the same problem. The offset classes were actually removed, but then restored in [PR 23445](https://github.com/twbs/bootstrap/pull/23445). Presumably the next release of bootstrap 4 beta will include them again.

**Comment by GusAndrianos** [comment]
@glebm I don't have a clue on how to compile the documentation. Can you help?

**Comment by glebm** [comment]
@GusAndrianos If you can't figure out how to compile the docs using the instructions at https://github.com/twbs/bootstrap, then you probably want to use the latest released version (4.0.0.beta released on August 11), not the master version. The docs for the latest release are available online at http://getbootstrap.com/.

**Comment by matanskii** [comment]
@bbugh Is there any way to integrate the fix (https://github.com/twbs/bootstrap/pull/23445) into my already running bootstrap gem?
