### ISSUE TITLE
Unable to use bootstrap variables from _bootstrap-variables.scss

### ISSUE THREAD

**Issue by mikeglaz** [twbs/bootstrap-rubygem#97]
I followed the directions on setting up this gem for Rails 5.1.2.  However, the following step does not work:
`// Custom bootstrap variables must be set or imported *before* bootstrap.`

I tried using the following
`$body-bg: $black;`
But this gives me a Sass::SyntaxError of Undefined variable.

Someone on SO suggests to keep the `require`s inside application.scss https://stackoverflow.com/questions/45000312/rails-5-bootstrap-4-how-do-i-turn-on-bootstrap-variables/45002091?noredirect=1#comment77100824_45002091

But that does not work either.

**Comment by glebm** [comment]
`$black` is not yet defined at that point. You need to also uncomment the line that defines it: https://github.com/twbs/bootstrap-rubygem/blob/b156edfee2b9629ad4751ee2a118a04f824ef9eb/templates/project/_bootstrap-variables.scss#L58

**Comment by mikeglaz** [comment]
I uncommented them in ~/.rvm/gems/ruby-2.4.0/bundler/gems/bootstrap-rubygem-b156edfee2b9/templates/project/_bootstrap-variables.scss

This did not work.

**Comment by glebm** [comment]
Not in the gem itself, but in your variables file

**Comment by mikeglaz** [comment]
I don't have one.  Maybe my question is how does it get created?

**Comment by glebm** [comment]
Yep, you can just copy that one, or put `$black:  #000;` in your file.
