### ISSUE TITLE
bootstrap4 navbar not working

### ISSUE THREAD

**Issue by cloudhuang** [twbs/bootstrap-rubygem#98]
With the "bootstrap-rubygem" latest version, the bootstrap 4 `navbar` not working as well.

**Comment by sofiazapatazavala** [comment]
I just updated the gem, and, for example, navbars now require a background declaration, by using a background utility or some custom code. Can you please be more specific about your problem? Also, refer to https://github.com/twbs/bootstrap-rubygem/issues/92 (bc we've all been there) and https://github.com/twbs/bootstrap/blob/6cf1a106d4fcd043f47d3eab4ffef3eaf868ce38/docs/4.0/migration.md to see if your problem is related to any migration issues.

**Comment by cloudhuang** [comment]
I create a new rails project and install this gem following the install guide, and using the bootstrap4 sample navbar

```
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
```

It should present like:
![image](https://user-images.githubusercontent.com/4601460/28194554-93ae9a64-6877-11e7-96ed-4fb3f8214f26.png)

But now it becomes
![image](https://user-images.githubusercontent.com/4601460/28194481-2026102c-6877-11e7-8158-8786c29d719d.png)

**Comment by glebm** [comment]
See https://github.com/twbs/bootstrap-rubygem/issues/96#issuecomment-314567699
