### ISSUE TITLE
Navbar not displaying correctly (Rails 5)

### ISSUE THREAD

**Issue by kleinjm** [twbs/bootstrap-rubygem#99]
I'm upgrading a Rails 5 app from Bootstrap 3 to 4. I'm using bootstrap (4.0.0.alpha6) gem and have @import "bootstrap"; as the only thing in my application.scss. I've taken the [navbar example](https://v4-alpha.getbootstrap.com/components/navbar/) right out of the box and it's displaying incorrectly on any screen size. I believe I've stripped down anything that could be interfering with it css-wise and not sure what else to try.
<img width="697" alt="screen shot 2017-07-20 at 4 41 37 pm" src="https://user-images.githubusercontent.com/2565158/28445014-52d33406-6d8f-11e7-84af-628aa7ec3b6a.png">
This is after clicking the left collapse button. It renders collapsed but not with the links on the bar itself.

**Comment by kleinjm** [comment]
It appears that the media queries are missing

**Comment by glebm** [comment]
Please see the related closed issues in this repo and the bold notice on top of the repo's readme.
